### ISSUE TITLE
Can't import library on python 3.7

### ISSUE THREAD

**Issue by UltraPhil** [brean/python-pathfinding#17]
Hi, using Python 3.7, I can't use the pathfinding module.

I've tried in an virtualenv and by installing it directly in the system packages.

Error is:
```
python.exe pathfinding.py
Traceback (most recent call last):
  File "pathfinding.py", line 1, in <module>
    from pathfinding.core.diagonal_movement import DiagonalMovement
  File "pathfinding.py", line 1, in <module>
    from pathfinding.core.diagonal_movement import DiagonalMovement
ModuleNotFoundError: No module named 'pathfinding.core'; 'pathfinding' is not a package

Process finished with exit code 1
```

Sample code used:
```
from pathfinding.core.diagonal_movement import DiagonalMovement
from pathfinding.finder.a_star import AStarFinder
from pathfinding.core.grid import Grid

matrix = [
    [1, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
]
grid = Grid(matrix=matrix)

start = grid.node(0, 0)
end = grid.node(2, 2)

finder = AStarFinder(diagonal_movement=DiagonalMovement.always)
path, runs = finder.find_path(start, end, grid)

print('operations:', runs, 'path length:', len(path))
print(grid.grid_str(path=path, start=start, end=end))
```

Any idea how to make it work?

**Comment by brean** [comment]
I guess you forgot to install pathfinding. You can use pip to install it either from pypi "pip install pathfinding" or if you cloned this git repo: "pip install pathfinding/" in the python-pathfinding-folder. After that the import should work.

**Comment by UltraPhil** [comment]
Thanks for your quick answer. I did install the path finding package both
in the system packages and in a virtualenv. I also did try on both Linux
and Windows 10 with brand new Python installations.

Steps to reproduce:
- take a new system
- install Python 3.7
- update pip (although upgrading it or not does not change outcome)
- pip install pathfinding
- try to run sample code


Best regards,

**Comment by brean** [comment]
Maybe you have a folder named "pathfinding" in your local folder that gets used instead of the installed one?
Or maybe there is another pathfinding-lib installed that is also named pathfinding? Try to do a `pip3 freeze` to see all installed versions. Also you should this lib which is `pathfinding==0.0.3`.
If that is the case I would be interested in the name of this other lib, so we can contact the author of this other lib to resolve the issue.

I don't know what else could be the problem, it is working on my machines (tested python 3.7 for Ubuntu 18.04 using pipenv and fedora 29 with pip3 and --user):

```
$ python3 --version
Python 3.7.2
$ pip3 install pathfinding --user
Collecting pathfinding
  Downloading https://files.pythonhosted.org/packages/43/ad/9ae1701f0c5bb005304b611ead7c6b0ae3efa5908fe574a4e33a17f0c734/pathfinding-0.0.3-py3-none-any.whl
Installing collected packages: pathfinding
Successfully installed pathfinding-0.0.3
$ python3
Python 3.7.2 (default, Jan 16 2019, 19:49:22) 
[GCC 8.2.1 20181215 (Red Hat 8.2.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathfinding.core.diagonal_movement import DiagonalMovement
>>> 
```

**Comment by brean** [comment]
Ah, I should have seen this earlier in your first question, your file is named pathfinding.py! Just rename it to something else! (e.g. path_finding.py) and you should be fine :smile: 
> python.exe pathfinding.py

**Comment by RphlBrdt** [comment]
Thank you so much. You have resolve our problem.
