### ISSUE TITLE
Using floats between 0 and 1 on the 2D list

### ISSUE THREAD

**Issue by alejcas** [brean/python-pathfinding#26]
Hi, I need to set some fields on the 2D matrix that have a 'walk cost' of a quarter of a movement point (0.2)
But when doing so, the pathfinding algorithm starts to do some weird things.
If I instead use only integers the pathfinding works just  great.

Is there any chance of using floats?

I'm using the A* algorithm.

**Comment by brean** [comment]
Interesting! In theory it should not make a difference. I tired to to recreate and fix it, but I wasn't successful so for now I'll mark this as a bug. I am not sure what causes the issue but I think it might have something to do with the way the path length gets calculated based on the heuristic.

The easiest workaround for now is to multiplay the weight with a bigger number like 100.

**Comment by brean** [comment]
fixed in 1.0.13.
I forgot to multiply the heuristic with the weight, see:
https://github.com/brean/python-pathfinding/blob/89ca95c1dd1387d6cd76162f1555dac4044f6e98/pathfinding/finder/finder.py#L77-L81
Sorry it took nearly 5 years, but I am very happy to finally have figure this out!
