### ISSUE TITLE
Show only adjacent path, not diagonal

### ISSUE THREAD

**Issue by TSecretT** [brean/python-pathfinding#32]
Hi, I would like to know if there is an option to split the path into either X-direction move, or Y-direction move, not X and Y at the same time (diagonal). Hope that makes sense for you. Thank you!

**Comment by brean** [comment]
If I understand correctly you want something like an algorithm you see sometimes in for example city-building games where you would use python-pathfinding to create a straight line (e.g. all the way to the left and then up) and not a staircase path to the goal.
For that you can easily create a new heuristic (see https://github.com/brean/python-pathfinding/blob/master/pathfinding/core/heuristic.py) where you just multiply x or y from manhattan with a larger number (10000 or something)

**Comment by TSecretT** [comment]
I am very new to such algorithms :) Basically, I am trying to implement pathfinding algorithm to find the shortest path for the Bomberman game and the problem is that path is being returned as red marks, and since the character can only move UP, DOWN, LEFT or RIGHT, the shortest path should be displayed with black marks. As I understood, I am using the wrong pathfinding method (DiagonalMovement)
![image](https://user-images.githubusercontent.com/36734601/89806474-e98a9580-db58-11ea-9c7e-b9c6b1799059.png)

**Comment by brean** [comment]
Ah, okay, I misunderstood what you want. It is actually already implemented, and very easy to use, you just need to set `diagonal_movement` to `DiagonalMovement.never` (or 2). Lets say you want to use A* then the code would look like this (assuming you already have start, end and grid defined):
``` python
from pathfinding.core.diagonal_movement import DiagonalMovement
from pathfinding.finder.a_star import AStarFinder

# set grid, start and end ...

finder = AStarFinder(diagonal_movement=DiagonalMovement.never)
path, runs = finder.find_path(start, end, grid)
print(grid.grid_str(path=path, start=start, end=end))
```

**Comment by TSecretT** [comment]
Perfect that's exactly what I've been looking for! Thank you! But I also had another issue, not sure if I should open another ticket for it. Sometimes I can't find the path even then it is relatively short and straight. Below is the code I am using, where `self.currPos` is an array [x, y] of my position, and `pos` is targe's position. It prints 25 operations, but 0 paths?

`matrix = self.getMatrix()
            grid = Grid(matrix=matrix)
            start = grid.node(self.currPos[0], self.currPos[1])
            end = grid.node(pos[0], pos[1])
            finder = AStarFinder(diagonal_movement=DiagonalMovement.always)
            path, runs = finder.find_path(start, end, grid)`

![image](https://user-images.githubusercontent.com/36734601/89809438-5dc73800-db5d-11ea-9a7d-8d1592a96839.png)

**Comment by TSecretT** [comment]
The issue has been solved by changing `diagonal_movement=DiagonalMovement.always` to `DiagonalMovement.never`
Thanks for help!
