### ISSUE TITLE
Slow Pathfinding for Larger Matrices

### ISSUE THREAD

**Issue by Ky-AnT** [brean/python-pathfinding#45]
I'm a user of the "pathfinding" Python module. It has greatly benefited my projects.
I've noticed the grid-to-string conversion function can be slow in some cases, especially with larger matrices like my 750x650 grid. On my laptop, it took around 29.89 seconds. I'm keen on optimizing this process. 
(The algorithm i'm using is bi-directional a*, which takes 8.54 seconds)

**Comment by brean** [comment]
fixed in 1.0.3
run `pip3 install pathfinding==1.0.3` to update
