### ISSUE TITLE
Bug when edges are defined from the end

### ISSUE THREAD

**Issue by Lalbatros** [brean/python-pathfinding#51]
Good afternoon,

I just realised that if a link is defined from the end of a path to be found, the `DijkstraFinder` seems to give absurd results:
```
from pathfinding.core.diagonal_movement import DiagonalMovement
from pathfinding.core.graph import Graph
from pathfinding.core.node import Node
from pathfinding.finder.a_star import AStarFinder

edges = [
    [0, 1, 1],
    [1, 0, 1],
    [1, 2, 1],
    [2, 1, 1],
]
graph = Graph(edges=edges, bi_directional=False)
finder = DijkstraFinder()
path, runs = finder.find_path(graph.node(0), graph.node(2), graph)
print(len(path), [n.node_id for n in path])
```
output: `1 [2]`

Comment the last edge out, and all is right again.

**Comment by brean** [comment]
Thank you! Nice catch!
Yes, this is a bug, that happens during the generation of the Graph, we are not checking if an element with the same id already exists, so there are multiple GraphNodes for number 2!
Funny side effect was that the order in which the elements are in your array are important, if you change the order to 
```python
    edges = [
        [0, 1, 1],
        [1, 0, 1],
        [2, 1, 1],
        [1, 2, 1],
    ]
```
it was also working... 
Anyway. I fixed it and will released the fix as version 1.0.5 !
