### ISSUE TITLE
Performance issue with node.py

### ISSUE THREAD

**Issue by peterchenadded** [brean/python-pathfinding#53]
We tried running below code

```
"""Test path finding performance."""
import numpy
from pathfinding.core.diagonal_movement import DiagonalMovement
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import pytest
import logging


class TestPathFinding:
    """Path finding test."""

    def _add_block(self, g: numpy.ndarray, x: int, y: int, padding: int):
        for i in range(x - padding, x + padding):
            for j in range(y - padding, y + padding):
                g[j][i] = 0

    # @pytest.mark.skip(reason="Please uncomment to enable")
    def test_performance(self):
        """Test performance."""
        # Get a 500 x 500 grid
        grid = numpy.ones((500, 500), numpy.int32)

        # Add a block at the center
        self._add_block(grid, 250, 250, 50)

        finder_grid = Grid(matrix=grid)
        start = finder_grid.node(0, 0)
        end = finder_grid.node(400, 400)

        finder = AStarFinder(diagonal_movement=DiagonalMovement.never)
        path, runs = finder.find_path(start, end, finder_grid)

        assert len(path) == 801
        logging.info("found len(path)=%s", len(path))

```

and did some profiling and found below bottleneck

<img width="685" alt="image" src="https://github.com/brean/python-pathfinding/assets/10074427/6f169fd9-6095-4f1d-8e9d-c47c740dd1ae">

i.e. to find a single path for a relative small grid it takes  34 seconds with debugger and 24 seconds without.

If we added below fixes:

<img width="1171" alt="image" src="https://github.com/brean/python-pathfinding/assets/10074427/b10208c7-bdb1-4cc7-af2c-88a127fbfeaf">

<img width="1191" alt="image" src="https://github.com/brean/python-pathfinding/assets/10074427/ba73201d-679e-43e6-a744-552c09356a4d">

We get much faster performance as shown below with 9 seconds with debugger and 7 seconds without.

<img width="674" alt="image" src="https://github.com/brean/python-pathfinding/assets/10074427/cc6203fd-219a-404c-bcf5-d8c98da0e152">

**Comment by peterchenadded** [comment]
PS: we really need to remove nsmallest from the implementation as that requires looping through the whole open_list which kind of defeats the purpose of using a heapq in the first place.

**Comment by brean** [comment]
Very good work! please provide a Pull Request!

**Comment by peterchenadded** [comment]
Alright this will take some time. Ran the tests and there lots of failures to go through.

**Comment by peterchenadded** [comment]
@brean, PR is created please review. Please note if we want to make it even faster the whole thing would need to be rewritten with numba in mind.

**Comment by brean** [comment]
merged. Thanks a lot!
I am not sure about numba, the idea of python-pathfinding was to be as little dependent on other libraries as possible, with education in mind, for performance I would probably go with a c++ wrapper in the first place.
However, with currently over 260 projects using python-pathfinding according to github, I think many of these might benefit from a numba-version, I am unsure how we can provide both.
A numby-version would probable be its own pathfinding-library and we can close this issue.

**Comment by peterchenadded** [comment]
> I am not sure about numba, the idea of python-pathfinding was to be as little dependent on other libraries as possible, with education in mind, for performance I would probably go with a c++ wrapper in the first place.

Yeah I agree.

> However, with currently over 260 projects using python-pathfinding according to github, I think many of these might benefit from a numba-version, I am unsure how we can provide both.

It would require a rewrite and lots of testing. Numba class support is in beta last I checked.

> A numba-version would probable be its own pathfinding-library and we can close this issue.

Yeah I agree too.

Thanks for getting this reviewed and merged so quickly.
